export class ServiceError extends Error{constructor(code,message,status=502){super(message);this.code=code;this.status=status;}}
const fail=()=>{throw new ServiceError('INVALID_PROVIDER_DATA','商家数据格式异常，请稍后重试。');};
const string=(s,max=200)=>typeof s==='string'&&s.trim().length>0&&s.length<=max;
export const coordinate=p=>p&&typeof p.lng==='number'&&Number.isFinite(p.lng)&&Math.abs(p.lng)<=180&&typeof p.lat==='number'&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90;
export function configured(env){try{return env.PROVIDER_VERIFIED==='true'&&string(env.MERCHANT_API_TOKEN,4096)&&new URL(env.MERCHANT_API_URL).protocol==='https:';}catch{return false;}}
export function parseQuery(params){const category=params.get('category')?.trim(),radius=Number(params.get('radius'));let location;try{location=JSON.parse(params.get('location'));}catch{}if(!string(category,12)||![3,5,10].includes(radius)||!location||!((location.kind==='region'&&string(location.label,40))||(location.kind==='coordinates'&&coordinate(location)&&location.coordType==='wgs84')))throw new ServiceError('INVALID_QUERY','请选择有效的品类、位置和查找范围。',400);return {category,radiusMeters:radius*1000,location:location.kind==='region'?{kind:'region',label:location.label.trim()}:{kind:'coordinates',lat:location.lat,lng:location.lng,coordType:'wgs84'},limit:50};}
export function meters(a,b){const rad=n=>n*Math.PI/180;const x=Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lng-a.lng)/2)**2;return 6371000*2*Math.atan2(Math.sqrt(Math.min(1,x)),Math.sqrt(Math.max(0,1-x)));}
export function normalize(payload,query){if(!payload||!string(payload.source,100)||payload.category!==query.category||!coordinate(payload.center)||payload.center.coordType!=='gcj02'||!Array.isArray(payload.shops)||payload.shops.length>200)fail();const ids=new Set();const shops=payload.shops.map(s=>{if(!s||!string(s.id,100)||!string(s.name)||!string(s.address,300)||!coordinate(s.location)||s.location.coordType!=='gcj02'||s.demo===true)fail();if(s.rating!=null&&(!Number.isFinite(s.rating)||s.rating<0||s.rating>5))fail();if(s.reviewCount!=null&&(!Number.isSafeInteger(s.reviewCount)||s.reviewCount<0))fail();if(s.positiveRate!=null&&(!Number.isFinite(s.positiveRate)||s.positiveRate<0||s.positiveRate>100))fail();return {id:s.id,name:s.name,address:s.address,location:{lng:s.location.lng,lat:s.location.lat,coordType:'gcj02'},rating:s.rating??null,reviewCount:s.reviewCount??null,positiveRate:s.positiveRate??null,distanceMeters:meters(payload.center,s.location)};}).filter(s=>{if(ids.has(s.id)||s.distanceMeters>query.radiusMeters)return false;ids.add(s.id);return true;}).sort((a,b)=>(b.rating??-1)-(a.rating??-1)||(b.reviewCount??-1)-(a.reviewCount??-1)||a.distanceMeters-b.distanceMeters||a.id.localeCompare(b.id)).slice(0,3);return {source:payload.source,category:query.category,shops};}
// Provider credentials and location resolution remain server-side. The upstream must
// resolve a named region and convert WGS-84 input to GCJ-02 before returning results.
export async function searchMerchants(query,env=process.env,fetcher=fetch){if(!configured(env))throw new ServiceError('NOT_CONFIGURED','商家数据未接入。',503);let response;try{response=await fetcher(env.MERCHANT_API_URL,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',Authorization:`Bearer ${env.MERCHANT_API_TOKEN}`},body:JSON.stringify(query),signal:AbortSignal.timeout(10000)});}catch{throw new ServiceError('PROVIDER_UNAVAILABLE','商家服务暂时不可用，请稍后重试。');}if(!response.ok)throw new ServiceError('PROVIDER_UNAVAILABLE',response.status===429?'商家服务查询额度暂时用尽，请稍后重试。':'商家服务暂时不可用，请稍后重试。');let payload;try{const text=await response.text();if(text.length>1000000)fail();payload=JSON.parse(text);}catch{fail();}return normalize(payload,query);}
