import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {createServer} from '../server.mjs';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/11858/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const out=new URL('../test-results/',import.meta.url);await mkdir(out,{recursive:true});
const server=createServer({});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}:{})});const results=[],errors=[];
const pass=s=>{results.push(s);console.log('PASS '+s);};
try{const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);assert.equal(await p.locator('.option').count(),0);assert.equal(await p.locator('#start').isDisabled(),true);for(const idea of ['火锅','烧烤','自助','小炒']){await p.locator('#new-idea').fill(idea);await p.locator('#add-form button').click();if(idea==='火锅')assert.equal(await p.locator('#start').isDisabled(),true);}
 await p.locator('[data-index="0"]').fill('  ');assert.equal(await p.locator('#start').isDisabled(),true);await p.locator('[data-index="0"]').fill('烧烤');assert.equal(await p.locator('#start').isDisabled(),true);await p.locator('[data-index="0"]').fill('面条');await p.locator('#new-idea').fill('米线');await p.locator('#add-form button').click();assert.equal(await p.locator('.option').count(),5);await p.getByRole('button',{name:'删除米线',exact:true}).click();for(const name of ['寿司','粤菜','披萨','牛排']){await p.locator('#new-idea').fill(name);await p.locator('#add-form button').click();}assert.equal(await p.locator('.option').count(),8);assert.equal(await p.locator('#add-form button').isDisabled(),true);await p.screenshot({path:fileURLToPath(new URL('ideas-mobile.png',out))});pass('选项编辑、空白、重复、增删及上限');
 await p.locator('#start').click();await p.screenshot({path:fileURLToPath(new URL('wheel-mobile.png',out))});await p.locator('#spin').click();assert.equal(await p.locator('#spin').isDisabled(),true);await p.evaluate(()=>document.querySelector('#spin').click());await p.waitForSelector('#chosen-category');let category=await p.locator('#chosen-category').textContent();assert.ok(['面条','烧烤','自助','小炒','寿司','粤菜','披萨','牛排'].includes(category));await p.screenshot({path:fileURLToPath(new URL('result-mobile.png',out))});pass('GO 防重复触发、自动进入独立结果页');
 await p.locator('#nearby').click();await p.getByRole('heading',{name:'商家数据未接入'}).waitFor();assert.equal(await p.locator('#choose-shop').isDisabled(),true);await p.screenshot({path:fileURLToPath(new URL('unconfigured-mobile.png',out))});pass('无凭证状态无虚构商家');
 await p.evaluate(()=>{Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition:(ok,fail)=>fail({code:1})}});});await p.locator('#change-location').click();await p.locator('#locate').click();assert.match(await p.locator('#location-error').textContent(),/定位未获授权/);await p.locator('#close-location').click();await p.getByRole('heading',{name:'定位未获授权'}).waitFor();pass('定位拒绝后可手动输入区域');
 let mode='few',queries=[],release;await p.route('**/api/config',r=>r.fulfill({json:{configured:true}}));const data=(category,count=1)=>({source:'自动测试虚构数据',category,shops:Array.from({length:count},(_,i)=>({id:String(i),name:`测试专用 · ${category}${i}`,address:`测试地址 ${i} 号`,rating:i?null:4.8,reviewCount:i?null:12,distanceMeters:1200+i*200,positiveRate:null,location:{lng:104.08+i*.001,lat:30.66,coordType:'gcj02'}}))});
 await p.route('**/api/shops?*',async route=>{const url=new URL(route.request().url()),q=Object.fromEntries(url.searchParams);queries.push(q);if(mode==='delay')await new Promise(r=>release=r);if(mode==='error')await route.fulfill({status:502,json:{code:'PROVIDER_UNAVAILABLE',message:'商家服务暂时不可用，请稍后重试。'}});else await route.fulfill({json:data(q.category,mode==='empty'?0:mode==='three'?3:1)});});
 await p.locator('#change-location').click();await p.locator('#region').fill('成都 · 春熙路');await p.locator('#location-form .primary').click();await p.locator('.shop').waitFor();assert.equal(queries.at(-1).category,category);assert.equal(queries.at(-1).radius,'3');assert.equal(JSON.parse(queries.at(-1).location).label,'成都 · 春熙路');assert.equal(await p.locator('.shop').count(),1);assert.equal(await p.getByText('好评率',{exact:false}).count(),0);await p.screenshot({path:fileURLToPath(new URL('shops-test-fixture.png',out))});await p.locator('.shop').click();await p.locator('#choose-shop').click();assert.match(await p.locator('.destination h2').textContent(),new RegExp(category));await p.locator('[data-map=amap]').click();let href=new URL(await p.locator('#navigate').getAttribute('href'));assert.match(href.searchParams.get('to'),/^104.08,30.66,/);await p.locator('[data-map="baidu"]').click();href=new URL(await p.locator('#navigate').getAttribute('href'));assert.match(href.searchParams.get('destination'),/^latlng:30.66,104.08/);await p.screenshot({path:fileURLToPath(new URL('destination-test-fixture.png',out))});pass('区域查询、品类同步、实际商家数量、来源标注、两种地图目标一致');
 await p.locator('.back').click();await p.locator('#expand').click();await p.waitForFunction(()=>document.querySelector('.shop')&&!document.querySelector('.shop.selected'));assert.equal(queries.at(-1).radius,'5');assert.equal(await p.locator('#choose-shop').isDisabled(),true);mode='empty';await p.locator('#radius').selectOption('10');await p.getByRole('heading',{name:'附近暂无匹配商家'}).waitFor();mode='error';await p.locator('#radius').selectOption('3');await p.getByRole('heading',{name:'暂时无法推荐商家'}).waitFor();mode='three';await p.locator('#state-action').click();await p.waitForFunction(()=>document.querySelectorAll('.shop').length===3);assert.equal(await p.locator('.shop').nth(1).locator('.score b').count(),0);pass('扩大范围清除选择、无结果、接口失败及重试、缺失评分');
 mode='delay';await p.locator('#radius').selectOption('5');await p.getByRole('heading',{name:'正在找附近的店'}).waitFor();await p.locator('.back').click();await p.locator('.back').click();await p.locator('.back').click();await p.locator('[data-index="0"]').fill('馄饨');if(release)release();await p.locator('#start').click();await p.locator('#spin').click();await p.waitForSelector('#chosen-category');category=await p.locator('#chosen-category').textContent();mode='few';await p.locator('#nearby').click();await p.locator('.shop').waitFor();assert.equal(queries.at(-1).category,category);assert.equal(await p.locator('#choose-shop').isDisabled(),true);pass('编辑及重新转动清除旧结果、旧推荐、旧选店；异步旧响应不会覆盖');
 await p.locator('.back').click();await p.locator('.back').click();await p.locator('.back').click();while(await p.locator('.option').count()>2)await p.locator('[data-delete]').last().click();assert.equal(await p.locator('[data-delete]:disabled').count(),0);pass('最少两个选项');await p.locator('#start').click();
 for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390},{width:667,height:375},{width:1280,height:800}]){await p.setViewportSize(size);const dims=await p.locator('.wheel-area').boundingBox();assert.ok(Math.abs(dims.width-dims.height)<1);assert.ok(dims.x>=0&&dims.y>=0&&dims.x+dims.width<=size.width&&dims.y+dims.height<=size.height);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await p.locator('.wheel-content').evaluate(e=>getComputedStyle(e).overflow),'clip');await p.screenshot({path:fileURLToPath(new URL(`wheel-${size.width}x${size.height}.png`,out))});}pass('320px 手机、横屏及桌面转盘保持圆形，无裁切和滚动条');
 await p.emulateMedia({reducedMotion:'no-preference'});await p.setViewportSize({width:844,height:390});await p.locator('#spin').click();await p.waitForTimeout(400);const during=await p.locator('.wheel-area').boundingBox();assert.ok(during.height<=390);assert.equal(await p.locator('#spin').isDisabled(),true);assert.equal(await p.locator('.back').isDisabled(),true);await p.waitForSelector('#chosen-category');const chosen=await p.locator('#chosen-category').textContent();await p.locator('.back').click();const index=await p.locator('#wheel').evaluate(el=>{const t=getComputedStyle(el).transform;const matrix=new DOMMatrix(t);let angle=Math.atan2(matrix.b,matrix.a)*180/Math.PI;angle=(angle+360)%360;return Math.floor(((360-angle)%360)/180);});assert.equal(['馄饨','烧烤'][index],chosen);pass('真实 3 秒动画期间禁止重复及编辑；停留扇区和结果一致');
 await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#spin').click();await p.waitForSelector('#chosen-category');await p.locator('#nearby').click();await p.locator('.shop').waitFor();await p.locator('.shop').click();await p.locator('#change-location').click();await p.evaluate(()=>{Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition:(ok,fail)=>fail({code:2})}});});await p.locator('#locate').click();assert.match(await p.locator('#location-error').textContent(),/定位失败/);assert.equal(await p.locator('#choose-shop').isDisabled(),true);await p.evaluate(()=>{Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition:ok=>ok({coords:{longitude:104.08,latitude:30.66}})}});});await p.locator('#locate').click();await p.locator('.shop').waitFor();const gps=JSON.parse(queries.at(-1).location);assert.equal(gps.kind,'coordinates');assert.equal(gps.coordType,'wgs84');assert.equal(gps.lng,104.08);assert.equal(await p.locator('#choose-shop').isDisabled(),true);pass('定位不可用后重试成功，传递真实坐标类型并清除旧选店');
 assert.deepEqual(errors,[]);pass('浏览器无 JavaScript 运行错误');
}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(new URL('browser-results.json',out),JSON.stringify({passed:results,errors},null,2));}




