// Integration test uses a real HTTP Worker adapter and stubbed Baidu responses only.
import http from 'node:http';import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {handle} from '../worker/jzmd-worker.js';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/11858/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const env={BAIDU_AK:'integration-test-key-not-real',ALLOWED_ORIGINS:''},calls=[];
const worker=http.createServer(async(req,res)=>{const response=await handle(new Request('https://worker.test'+req.url,{method:req.method,headers:req.headers}),env,async address=>{const u=new URL(address);calls.push(u);if(u.pathname==='/geoconv/v2/')return Response.json({status:0,result:[{x:104.0865,y:30.666}]});return Response.json({status:0,results:[{uid:'test-shop',name:'测试专用餐厅',address:'测试地址',location:{lng:104.087,lat:30.667},detail_info:{overall_rating:'4.7'}}]});});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());});
await new Promise(r=>worker.listen(0,'127.0.0.1',r));const workerBase=`http://127.0.0.1:${worker.address().port}`;
const allowed=['index.html','app.js','core.js','style.css','favicon.svg','success.wav'];
const front=http.createServer(async(req,res)=>{if(req.url==='/config.json'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({configured:true,workerBaseUrl:workerBase}));return;}const name=req.url==='/'?'index.html':req.url.slice(1);if(!allowed.includes(name)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.wav')?'audio/wav':'text/html');res.setHeader('Content-Security-Policy',`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' ${workerBase}`);res.end(await readFile(new URL('../public/'+name,import.meta.url)));});
await new Promise(r=>front.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${front.address().port}`;env.ALLOWED_ORIGINS=base;
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}:{})});
try{const context=await browser.newContext({viewport:{width:390,height:844},permissions:['geolocation'],geolocation:{latitude:30.66,longitude:104.08},reducedMotion:'reduce'});const p=await context.newPage(),requests=[],errors=[];p.on('request',r=>requests.push(r.url()));p.on('pageerror',e=>errors.push(e.message));await p.goto(base);for(const idea of ['火锅','烧烤']){await p.locator('#new-idea').fill(idea);await p.locator('#add-form button').click();}await p.locator('#start').click();await p.locator('#spin').click();await p.waitForSelector('#chosen-category');const category=await p.locator('#chosen-category').textContent();await p.locator('#nearby').click();await p.locator('.shop').waitFor();
 assert.equal(calls.at(-1).searchParams.get('query'),category);assert.equal(calls[0].searchParams.get('coords'),'104.08,30.66');assert.equal(await p.locator('.shop').count(),1);assert.equal(await p.getByText('评价数量未提供').count(),0);assert.match(await p.locator('.shop').textContent(),/4.7 分/);assert.match(await p.locator('.shop').textContent(),/104.08700/);
 assert.ok(requests.some(u=>u.startsWith(workerBase+'/api/shops?')));assert.ok(requests.every(u=>!u.includes(env.BAIDU_AK)&&!u.includes('api.map.baidu.com')));
 await p.locator('.shop').click();await p.locator('#choose-shop').click();const nav=new URL(await p.locator('#navigate').getAttribute('href'));assert.equal(nav.hostname,'api.map.baidu.com');assert.equal(nav.searchParams.get('coord_type'),'bd09ll');assert.match(nav.searchParams.get('destination'),/^latlng:30.667,104.087/);
 await p.setViewportSize({width:844,height:390});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS front → geolocation → cross-origin Worker → Baidu adapter → result → correct BD09 navigation; no AK in browser requests');
}finally{await browser.close();await new Promise(r=>front.close(r));await new Promise(r=>worker.close(r));}

